db:
  image: postgres:11
app:
  # image: chbrown/typing-evaluation
  build: .
  ports:
    - "80:80"
  links:
    - db
  environment:
    - ADMIN_USER=open
    - ADMIN_PASS=sesame
    - VIRTUAL_HOST=typingexperiment.com
  restart: always
nginx:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/etc/nginx/certs:/etc/nginx/certs"
    - "/var/run/docker.sock:/tmp/docker.sock"
