version: "3"
services:
  db:
    image: postgres:11
    ports:
      - "5432"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=openpostgresesame
  app:
    # build: .
    image: chbrown/typing-evaluation:2.0.2
    ports:
      - "80:80"
    links:
      - db
    environment:
      - ADMIN_USER=open
      - ADMIN_PASS=sesame
      - PGHOST=db
      - PGPASSWORD=openpostgresesame
    restart: unless-stopped
volumes:
  database:
